COMMENT = Modular status bar for dwm written in c.
VERSION = 0.c8cedd220
REVISION = 0
CATEGORIES = xapps
PKGNAME = dwmblocks
HOMEPAGE = https://github.com/torrinfail/dwmblocks
SRCCD = git
BUILD = make
BUILDDIR = dwmblocks
MAKEOPT = CFLAGS=-std=gnu17

prepare:
	vim ${BUILDDIR}/blocks.def.h

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
