COMMENT = A collection of add-ons for the CMake build tool
VERSION = 1.10
REVISION = 0
CATEGORIES = devel
PKGNAME = cmake_extras
HOMEPAGE = https://gitlab.com/ubports/development/core/cmake-extras
ARCHIVE = cmake-extras-1.10.tar.gz
LINK = https://gitlab.com/ubports/development/core/cmake-extras/-/archive/1.10/cmake-extras-1.10.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = cmake-extras-1.10
BUILD_OPTION = -DCMAKE_BUILD_TYPE=None
STRIP = no

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
