COMMENT = Named, vector icons for elementary OS
VERSION = 8.2.0
REVISION = 0
CATEGORIES = icon
PKGNAME = elementary_icon
HOMEPAGE = https://github.com/elementary/icons
ARCHIVE = 8.2.0.tar.gz
LINK = https://github.com/elementary/icons/archive/refs/tags/8.2.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = icons-8.2.0
BUILD_OPTION = -Dvolume_icons=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
