COMMENT = GNU tool for automatically creating Makefiles
VERSION = 1.18.1
REVISION = 0
CATEGORIES = tool
PKGNAME = automake
HOMEPAGE = https://www.gnu.org/software/automake
ARCHIVE = automake-1.18.1.tar.xz
LINK = https://ftp.gnu.org/gnu/automake/automake-1.18.1.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = automake-1.18.1
BUILD_OPTION =
AUTO_CONF = (cd ${BUILDDIR} && ./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=/usr/lib \
	--build=x86_64-pc-linux-musl)
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
