COMMENT = Modular Wayland compositor library
VERSION = 0.20.c436bcf9a
_WLR = 436bcf9a4755b24f7fadc100ba8deaa7f343ba86
REVISION = 0
CATEGORIES = libs
PKGNAME = wlroots_git
HOMEPAGE = https://gitlab.freedesktop.org/wlroots/wlroots
ARCHIVE = wlroots-${_WLR}.tar.gz
LINK = https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/${_WLR}/wlroots-${_WLR}.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = wlroots-${_WLR}
BUILD_OPTION = -Dexamples=false -Dxwayland=enabled

prepare:

post_build:

include /usr/share/mk/lfs.port.mk
