COMMENT = Modular Wayland compositor library
VERSION = 0.21.c2cec06a4
_WLR = 2cec06a4617cd9c712c6b35831cd1d75c41fe2af
REVISION = 0
CATEGORIES = libs
PKGNAME = wlroots_git
HOMEPAGE = https://gitlab.freedesktop.org/wlroots/wlroots
ARCHIVE = wlroots-${_WLR}.tar.gz
LINK = ${HOMEPAGE}/-/archive/${_WLR}/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = wlroots-${_WLR}
BUILD_OPTION = -Dexamples=false -Dxwayland=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
