COMMENT = Generic lossless compressor
VERSION = 1.2.0
REVISION = 0
CATEGORIES = tool
PKGNAME = brotli
HOMEPAGE = https://github.com/google/brotli
ARCHIVE = v1.2.0.tar.gz
LINK = https://github.com/google/brotli/archive/refs/tags/v1.2.0.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = brotli-1.2.0
BUILD_OPTION = -DCMAKE_BUILD_TYPE=Release

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
