COMMENT = Manual tiling window manager
VERSION = 0.9.6
REVISION = 0
CATEGORIES = x11
PKGNAME = herbstluftwm
HOMEPAGE = https://herbstluftwm.org
ARCHIVE = herbstluftwm-0.9.6.tar.gz
LINK =  https://herbstluftwm.org/tarballs/herbstluftwm-0.9.6.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = herbstluftwm-0.9.6
BUILD_OPTION = -DCMAKE_BUILD_TYPE=MinSizeRel \
	-DBASHCOMPLETIONDIR=/usr/share/bash-completion/completions

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
