COMMENT = Library for pixel manipulation.
VERSION = 0.46.4
REVISION = 0
CATEGORIES = libs
PKGNAME = pixman
HOMEPAGE = https://www.x.org
ARCHIVE = pixman-0.46.4.tar.gz
LINK = https://www.cairographics.org/releases/pixman-0.46.4.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = pixman-0.46.4
BUILD_OPTION = --buildtype=release -Dtests=disabled \
	-Ddefault_library=both -Ddemos=disabled
LDFLAGS = -Wl,-z,stack-size=2097152
export LDFLAGS

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
