COMMENT =
VERSION =
REVISION =
CATEGORIES =
PKGNAME =
HOMEPAGE =
SRCCD =
ARCHIVE =
LINK =
BUILD =
BUILDDIR =
BUILD_OPTION =
AUTO_CONF =
MKINST = yes
MAKEOPT =

prepare:

# custom-build:
#

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
