COMMENT = GTK+ frontend to various command line archivers
VERSION = 0.5.4.26
REVISION = 0
CATEGORIES = xapps
PKGNAME = xarchiver
HOMEPAGE = https://github.com/ib/xarchiver
ARCHIVE = 0.5.4.26.tar.gz
LINK = https://github.com/ib/xarchiver/archive/0.5.4.26.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = xarchiver-0.5.4.26
BUILD_OPTION =
AUTO_CONF = (cd ${BUILDDIR} && ./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=/usr/lib \
	--build=x86_64-pc-linux-musl)
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
