COMMENT = Wayland tiling compositor inspired by Ratpoison
VERSION = 3.1.0
REVISION = 0
CATEGORIES = wayland
PKGNAME = cagebreak
HOMEPAGE = https://github.com/project-repo/cagebreak
ARCHIVE = 3.1.0.tar.gz
LINK = https://github.com/project-repo/cagebreak/archive/3.1.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = cagebreak-3.1.0
BUILD_OPTION = -Dman-pages=true -Dxwayland=true

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
