COMMENT = Python bindings for the GObject library
VERSION = 3.54.5
REVISION = 0
CATEGORIES = libs
PKGNAME = pygobject3
HOMEPAGE = https://wiki.gnome.org/Projects/PyGObject/
ARCHIVE = pygobject-3.54.5.tar.gz
LINK = https://download.gnome.org/sources/pygobject/3.54/pygobject-3.54.5.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = pygobject-3.54.5
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
