COMMENT = Wallpaper daemon for Wayland
VERSION = 1.2.1
REVISION = 0
CATEGORIES = wayland
PKGNAME = swaybg
HOMEPAGE = https://codeberg.org/swaywm/swaybg
ARCHIVE = swaybg-1.2.1.tar.gz
LINK = https://github.com/swaywm/swaybg/archive/v1.2.1/swaybg-1.2.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = swaybg-1.2.1
BUILD_OPTION = -Dman-pages=disabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
