COMMENT = A simple library-based package manager
VERSION = 7.1.0
REVISION = 0
CATEGORIES = tool
PKGNAME = pacman
HOMEPAGE = https://www.archlinux.org/pacman/
ARCHIVE = pacman-v7.1.0.tar.gz
LINK = https://gitlab.archlinux.org/pacman/pacman/-/archive/v7.1.0/pacman-v7.1.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = pacman-v7.1.0
BUILD_OPTION = -Dscriptlet-shell=/usr/bin/bash

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
