COMMENT = minimal terminal emulator for wayland
VERSION = 0.7.0
REVISION = 0
CATEGORIES = wayland
PKGNAME = havoc
HOMEPAGE = https://github.com/ii8/havoc
ARCHIVE = 0.7.0.tar.gz
LINK = https://github.com/ii8/havoc/archive/refs/tags/0.7.0.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = havoc-0.7.0
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
