COMMENT = Fully feature complete YAML parser and emitter
VERSION = 0.9.6
REVISION = 1
CATEGORIES = libs
PKGNAME = libfyaml
HOMEPAGE = https://github.com/pantoniou/libfyaml
ARCHIVE = libfyaml-0.9.6.tar.gz
LINK = https://github.com/pantoniou/libfyaml/releases/download/v0.9.6/libfyaml-0.9.6.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = libfyaml-0.9.6
BUILD_OPTION = -DENABLE_LIBCLANG=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
