COMMENT = GNOME desktop core libraries
VERSION = 44.1
REVISION = 0
CATEGORIES = misc
PKGNAME = gnome_desktop
HOMEPAGE = https://gitlab.gnome.org/GNOME/gnome-desktop
ARCHIVE = gnome-desktop-44.1.tar.xz
LINK = https://download.gnome.org/sources/gnome-desktop/44/gnome-desktop-44.1.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = gnome-desktop-44.1
BUILD_OPTION = -Dudev=enabled -Dbuild_gtk4=true -Dlegacy_library=true

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
