COMMENT = Dynamic menu library and client program with support for different backends
VERSION = 0.6.23
REVISION = 0
CATEGORIES = xapps
PKGNAME = bemenu
HOMEPAGE = https://github.com/Cloudef/bemenu
ARCHIVE = 0.6.23.tar.gz
LINK = https://github.com/Cloudef/bemenu/archive/0.6.23.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = bemenu-0.6.23
MAKEOPT = CFLAGS="-g" 

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
