COMMENT = A Sample Authorization Protocol for X
VERSION = 1.0.12
REVISION = 0
CATEGORIES = libs
PKGNAME = libXau
HOMEPAGE = https://www.x.org
ARCHIVE = libXau-${VERSION}.tar.gz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXau-${VERSION}
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --libdir=/usr/lib) 

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
