COMMENT = C++ bindings for pango
VERSION = 2.46.4
REVISION = 0
CATEGORIES = libs
PKGNAME = pangomm2.46
HOMEPAGE = https://www.gtkmm.org/
ARCHIVE = pangomm-2.46.4.tar.xz
LINK = https://download.gnome.org/sources/pangomm/2.46/pangomm-2.46.4.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = pangomm-2.46.4
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
