COMMENT = X.Org X11 libXfont2 runtime library
VERSION = 2.0.7
REVISION = 0
CATEGORIES = libs
PKGNAME = libXfont2
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXfont2-2.0.7.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXfont2-2.0.7
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
