COMMENT = scrollable, floating window manager for Wayland 
VERSION = 0.cd6aac9c3
REVISION = 0
CATEGORIES = wayland
PKGNAME = hevel
HOMEPAGE = https://git.sr.ht/~dlm/hevel
SRCCD = git
BUILD = make
BUILDDIR = hevel

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
