COMMENT = Incremental parsing system for programming tools
VERSION = 0.26.7
REVISION = 1
CATEGORIES = tool
PKGNAME = tree_sitter
HOMEPAGE = https://tree-sitter.github.io/
ARCHIVE = v0.26.7.tar.gz 
LINK = https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.26.7.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = tree-sitter-0.26.7
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
