COMMENT = Library for JPEG images.
VERSION = 3.1.3
REVISION = 0
CATEGORIES = libs
PKGNAME = libjpeg_turbo
HOMEPAGE = https://libjpeg-turbo.org/
ARCHIVE = libjpeg-turbo-3.1.3.tar.gz
LINK = https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/3.1.3/libjpeg-turbo-3.1.3.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = libjpeg-turbo-3.1.3
BUILD_OPTION = -DCMAKE_BUILD_TYPE=Release -DWITH_JPEG8=1

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
