COMMENT = Library that extends GTK with common widgets and utilities
VERSION = 6.2.0
REVISION = 0
CATEGORIES = libs
PKGNAME = granite
HOMEPAGE = https://github.com/elementary/granite
ARCHIVE = granite-6.2.0.tar.gz
LINK = https://github.com/elementary/granite/archive/6.2.0/granite-6.2.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = granite-6.2.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
