COMMENT = i3-compatible window manager for Wayland 
VERSION = 0.11.cfa497964.r7636
_REV = fa497964fd55632beacf5f425e964ae4893e25b9
REVISION = 0
CATEGORIES = wayland
PKGNAME = sway
HOMEPAGE = https://github.com/swaywm/sway
ARCHIVE = ${_REV}.tar.gz
LINK = ${HOMEPAGE}/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = sway-${_REV}
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
