COMMENT = i3-compatible window manager for Wayland 
VERSION = 0.13.c6959a78a
_REV = 6959a78a8f0d52f79ad7465135b3295307a5146a
REVISION = 0
CATEGORIES = wayland
PKGNAME = sway
HOMEPAGE = https://github.com/swaywm/sway
ARCHIVE = ${_REV}.tar.gz
LINK = ${HOMEPAGE}/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = sway-${_REV}
BUILD_OPTION = -Dgdk-pixbuf=enabled -Dtray=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
