COMMENT = ISO country, language, script and currency codes and translations.
VERSION = 4.20.1
COMMIT = 74623235ae99f6e835e1e465017ce4c544ae6b53
REVISION = 0
CATEGORIES = misc
PKGNAME = iso_codes
HOMEPAGE = https://salsa.debian.org/iso-codes-team/iso-codes
ARCHIVE = iso-codes-4.20.1.tar.bz2
LINK = https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v4.20.1/iso-codes-4.20.1.tar.bz2
SRCCD = archive
BUILD = meson
BUILDDIR = iso-codes-v${VERSION}-${COMMIT}
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
