COMMENT = Library that extends GTK with common widgets and utilities
VERSION = 7.8.1
REVISION = 0
CATEGORIES = libs
PKGNAME = granite7
HOMEPAGE = https://github.com/elementary/granite
ARCHIVE = granite-7.8.1.tar.gz
LINK = https://github.com/elementary/granite/archive/7.8.1/granite-7.8.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = granite-7.8.1
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
