COMMENT = XML-XCB protocol descriptions
VERSION = 1.17.0
REVISION = 0
CATEGORIES = libs
PKGNAME = xcb_proto
HOMEPAGE = https://xcb.freedesktop.org
ARCHIVE = xcb-proto-${VERSION}.tar.xz
LINK = https://xorg.freedesktop.org/archive/individual/proto/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = xcb-proto-${VERSION}
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr) 

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
