COMMENT = Library full of GTK+ widgets for mobile phones
VERSION = 1.8.3
REVISION = 0
CATEGORIES = libs
PKGNAME = libhandy1
HOMEPAGE = https://gitlab.gnome.org/GNOME/libhandy
ARCHIVE = libhandy-1.8.3.tar.xz
LINK = https://download.gnome.org/sources/libhandy/1.8/libhandy-1.8.3.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = libhandy-1.8.3
BUILD_OPTION = -Dexamples=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
