COMMENT = Simple Directmedia Layer.
VERSION = 2.32.10
REVISION = 0
CATEGORIES = libs
PKGNAME = SDL2
HOMEPAGE = https://www.libsdl.org/
ARCHIVE = SDL2-2.32.10.tar.gz
LINK = https://libsdl.org/release/SDL2-2.32.10.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = SDL2-2.32.10
BUILD_OPTION = -DSDL_STATIC_PIC=ON -DSDL_STATIC=ON -DSDL_WAYLAND=ON

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
