COMMENT = Stacking small wlroots window manager
VERSION = 0.3.2.c26474fc1
_SHA = 26474fc1b43a17ed3dc228b2e804fbc29f959189
REVISION = 0
CATEGORIES = wayland
PKGNAME = steppewm
HOMEPAGE = https://keygen.sbs/steppewm
ARCHIVE = ${_SHA}.tar.gz
LINK = https://github.com/uncognic/steppewm/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = steppewm-${_SHA}
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
