COMMENT = Text file format converters
VERSION = 7.5.6
REVISION = 0
CATEGORIES = tool
PKGNAME = dos2unix
HOMEPAGE = https://waterlan.home.xs4all.nl/dos2unix.html
ARCHIVE = dos2unix-${VERSION}.tar.gz
LINK = https://waterlander.net/dos2unix/files/dos2unix-${VERSION}.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = dos2unix-${VERSION}
MAKEOPT = ENABLE_NLS= prefix=/usr libdir=/usr docsubdir=${PKGNAME}

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
