COMMENT =EDID and DisplayID library
VERSION =0.3.0
REVISION =0
CATEGORIES =libs
PKGNAME =libdisplay_info
HOMEPAGE =https://gitlab.freedesktop.org/emersion/libdisplay-info
ARCHIVE =libdisplay-info-${VERSION}.tar.gz
LINK =https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive/${VERSION}/${ARCHIVE}
SRCCD =archive
BUILD =meson
BUILDDIR =libdisplay-info-${VERSION}

prepare:

post_build:

include /usr/share/mk/lfs.port.mk
