COMMENT = A multipurpose and versatile launcher / picker for Hyprland
VERSION = 0.1.5
REVISION = 0
CATEGORIES = wayland
PKGNAME = hyprlauncher
HOMEPAGE = https://github.com/hyprwm/hyprlauncher
ARCHIVE = hyprlauncher-0.1.5.tar.gz
LINK = https://github.com/hyprwm/hyprlauncher/archive/v0.1.5/hyprlauncher-0.1.5.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = hyprlauncher-0.1.5
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
