COMMENT = Hyprland utilities library used across the ecosystem
VERSION = 0.11.0
REVISION = 0
CATEGORIES = libs
PKGNAME = hyprutils
HOMEPAGE = https://github.com/hyprwm/hyprutils
ARCHIVE = hyprutils-v0.11.0.tar.gz
LINK = https://github.com/hyprwm/hyprutils/archive/v0.11.0/hyprutils-v0.11.0.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = hyprutils-0.11.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
