COMMENT = A fork of i3wm tiling window manager with more features, including gaps
VERSION = 4.21.1
REVISION = 1
CATEGORIES = x11-wm
PKGNAME = i3gaps
HOMEPAGE = https://github.com/Airblader/i3
ARCHIVE = 4.21.1.tar.gz
LINK = https://github.com/Airblader/i3/archive/4.21.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = i3-4.21.1
BUILD_OPTION = -Ddocs=true -Dmans=true

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
