COMMENT = An HTML5 parsing library in pure C99
VERSION = 0.13.2
REVISION = 0
CATEGORIES = libs
PKGNAME = gumbo_parser
HOMEPAGE = https://codeberg.org/grisha/gumbo-parser
ARCHIVE = 0.13.2.tar.gz
LINK = https://codeberg.org/grisha/gumbo-parser/archive/0.13.2.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = gumbo-parser
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
