COMMENT = Lightweight KMS plane library
VERSION = 0.5.0
REVISION = 0
CATEGORIES = libs
PKGNAME = libliftoff
HOMEPAGE = https://gitlab.freedesktop.org/emersion/libliftoff
ARCHIVE = libliftoff-v${VERSION}.tar.gz
LINK = ${HOMEPAGE}/-/archive/v${VERSION}/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = libliftoff-v${VERSION}

prepare:

post_build:

include /usr/share/mk/lfs.port.mk
