COMMENT = Hyprland GUI utilities
VERSION = 0.2.1
REVISION = 0
CATEGORIES = wayland
PKGNAME = hyprland-guiutils
HOMEPAGE = https://github.com/hyprwm/hyprland-guiutils
ARCHIVE = hyprland-guiutils-0.2.1.tar.gz
LINK = https://github.com/hyprwm/hyprland-guiutils/archive/v0.2.1/hyprland-guiutils-0.2.1.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = hyprland-guiutils-0.2.1
BUILD_OPTION = -DCMAKE_BUILD_TYPE=Release

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
