COMMENT = tint2 is a simple unintrusive panel/taskbar
VERSION = 17.1.3
REVISION = 0
CATEGORIES = xapps
PKGNAME = tint2
HOMEPAGE = https://gitlab.com/nick87720z/tint2/
ARCHIVE = tint2-17.1.3.tar.bz2
LINK = https://gitlab.com/nick87720z/tint2/-/archive/17.1.3/tint2-17.1.3.tar.bz2
SRCCD = archive
BUILD = cmake
BUILDDIR = tint2-17.1.3
BUILD_OPTION = -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
			-DCMAKE_BUILD_TYPE=None

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
