COMMENT = GTK4 widget to display maps
VERSION = 1.6.2
REVISION = 0
CATEGORIES = libs
PKGNAME = libshumate
HOMEPAGE = https://gitlab.gnome.org/GNOME/libshumate
ARCHIVE = libshumate-1.6.2.tar.gz
LINK = https://gitlab.gnome.org/GNOME/libshumate/-/archive/1.6.2/libshumate-1.6.2.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = libshumate-1.6.2
BUILD_OPTION = -Dgtk_doc=false \
	-Dvector_renderer=true \
	-Dsysprof=disabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
