COMMENT = X11 font encoding library
VERSION = 1.1.8
REVISION = 0
CATEGORIES = libs
PKGNAME = libfontenc
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libfontenc-1.1.8.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libfontenc-1.1.8
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
