COMMENT = A fast math parser library
VERSION = 2.3.5
REVISION = 1
CATEGORIES = libs
PKGNAME = muparser
HOMEPAGE = https://github.com/beltoforion/muparser
ARCHIVE = muparser-2.3.5.tar.gz
LINK = https://github.com/beltoforion/muparser/archive/v2.3.5/muparser-2.3.5.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = muparser-2.3.5
BUILD_OPTION = -Wno-dev

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
