COMMENT = Lightweight brightness control tool
VERSION = 0.5.1
REVISION = 0
CATEGORIES = tool
PKGNAME = brightnessctl
HOMEPAGE = https://github.com/Hummer12007/brightnessctl
ARCHIVE = 0.5.1.tar.gz
LINK = https://github.com/Hummer12007/brightnessctl/archive/0.5.1.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = brightnessctl-0.5.1
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
