COMMENT = Interaction screen selection on Wayland compositors.
VERSION = 1.5.0
REVISION = 0
CATEGORIES = tool
PKGNAME = slurp
HOMEPAGE = https://wayland.emersion.fr/slurp/
ARCHIVE = slurp-1.5.0.tar.gz
LINK = https://github.com/emersion/slurp/archive/v1.5.0/slurp-1.5.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = slurp-1.5.0
BUILD_OPTION = -Dman-pages=disabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
